# 实验名称
experiment: "CAN"

# 随机种子
seed: 20211024

# 训练参数
epochs: 240
batch_size: 2
workers: 0
train_parts: 1
valid_parts: 1
valid_start: 0
save_start: 0

optimizer: Adadelta
lr: 1
lr_decay: cosine
step_ratio: 10
step_decay: 5
eps: 1e-6
weight_decay: 1e-4
beta: 0.9

dropout: True
dropout_ratio: 0.5
relu: True
gradient: 100
gradient_clip: True
use_label_mask: False

# 路径
base_dir: 'alignment/step1-5/'
result_dir: 'alignment/result'

# 参数路径
paddle_params_path: 'data/can_148.pdparams'
torch_params_path: 'data/can_148.pth'

# 假数据
fake_data_path: 'data/fake_data.npy'
fake_data_mask_path: 'data/fake_data_mask.npy'
fake_label_path: 'data/fake_label.npy'
fake_label_mask_path: 'data/fake_label_mask.npy'

# 轻量训练数据
train_image_path: 'lite_data/lite_images.pkl'
train_label_path: 'lite_data/lite_labels.txt'

# 字典路径
word_path: 'lite_data/words_dict.txt'

# collate_fn
collate_fn: collate_fn
word_num : 111

densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

encoder:
  input_channel: 1
  out_channel: 684

decoder:
  net: AttDecoder
  cell: 'GRU'
  input_size: 256
  hidden_size: 256
  

counting_decoder:
  in_channel: 684
  out_channel: 111

attention:
  attention_dim: 512
  word_conv_kernel: 1

attention_map_vis_path: 'vis/attention_map'
counting_map_vis_path: 'vis/counting_map'

whiten_type: None
max_step: 256

optimizer_save: False
finetune: False
checkpoint_dir: 'checkpoints'
checkpoint: ""
log_dir: 'logs'
